const fs = require('fs');

const data = [
  ["Application", "Group", "Parameter", "Value Type", "Normal / Before Trial", "Trial / After Trial"],
  ["Pipe-Fitting", "General Information", "Trial No.", "Information", "14", ""],
  ["Pipe-Fitting", "General Information", "Purpose", "Information", "Increase Calcium from 9 to 11 kg", ""],
  ["Pipe-Fitting", "General Information", "Preparing Date", "Information", "2026-08-04", ""],
  ["Pipe-Fitting", "General Information", "Mixing Date", "Information", "2026-08-04", ""],
  ["Fitting", "General Information", "Pelletizing Date", "Information", "2026-08-05", ""],
  ["Pipe-Fitting", "General Information", "Trial or Normal run Date", "Information", "2026-08-19", ""],
  ["Pipe-Fitting", "General Information", "No. Of People", "Information", "", ""],
  ["Pipe-Fitting", "General Information", "Material Handover", "Information", "Delivered to Production", ""],
  ["Pipe-Fitting", "General Information", "Received By / Doc No", "Information", "1234", ""],
  ["Pipe-Fitting", "Formulation", "Formula Code", "Comparison", "KH 920", "KH 570"],
  ["Pipe-Fitting", "Formulation", "No. of Batches", "Information", "1", ""],
  ["Pipe-Fitting", "Formulation", "PVC 57", "Comparison", "300", ""],
  ["Pipe-Fitting", "Formulation", "Calcium Carbonate", "Comparison", "9", "11"],
  ["Pipe-Fitting", "Formulation", "Stabilizer", "Comparison", "12", ""],
  ["Pipe-Fitting", "Formulation", "Titanium Dioxide, 134a", "Comparison", "9", ""],
  ["Pipe-Fitting", "Formulation", "Lub., LP-551", "Comparison", "1.44", ""],
  ["Pipe-Fitting", "Formulation", "Lub., SAG-Lub 12", "Comparison", "1.8", ""],
  ["Pipe-Fitting", "Formulation", "Lub., Finalux G1", "Comparison", "1.5", ""],
  ["Pipe-Fitting", "Formulation", "Lub., Finalux G322", "Comparison", "2.1", ""],
  ["Pipe-Fitting", "Formulation", "PE Wax", "Comparison", "0.6", ""],
  ["Pipe-Fitting", "Formulation", "ESBO", "Comparison", "0.9", ""],
  ["Pipe-Fitting", "Formulation", "Calcium Sterate", "Comparison", "0.45", ""],
  ["Pipe-Fitting", "Formulation", "Total", "Calculated", "340.79", ""],
  ["Pipe-Fitting", "Machine Information", "Machine", "Information", "MC / 07", ""],
  ["Fitting", "Machine Information", "M/C Clamp Force (Tons)", "Information", "", ""],
  ["Pipe-Fitting", "Product Information", "Product", "Information", "4 inch 45 deg. Elbo", ""],
  ["Pipe-Fitting", "Product Information", "Product Code", "Information", "502", ""],
  ["Pipe-Fitting", "Product Information", "Color", "Information", "White", ""],
  ["Fitting", "Product Information", "No. of Cavities", "Information", "2", ""],
  ["Pipe-Fitting", "Product Information", "Product Weight (kg)", "Comparison", "0.46", ""],
  ["Fitting", "Product Information", "Runner Weight (kg)", "Comparison", "0.07", ""],
  ["Pipe-Fitting", "Common Processing Parameters", "Screw RPM", "Comparison", "", ""],
  ["Fitting", "Injection Parameters", "Filling Time (s)", "Comparison", "14.69", "14.77"],
  ["Pipe-Fitting", "Injection Parameters", "Cycle Time (s)", "Comparison", "101.7", "101.81"],
  ["Fitting", "Injection Parameters", "Cooling Time (s)", "Comparison", "60", ""],
  ["Fitting", "Injection Parameters", "Refilling Time (s)", "Comparison", "43", "42.54"],
  ["Fitting", "Injection Parameters", "Shot Size (mm)", "Comparison", "175", ""],
  ["Fitting", "Injection Parameters", "Cushion (mm)", "Comparison", "9.8", "10.4"],
  ["Fitting", "Injection Parameters", "Hold on Pressure P1", "Comparison", "75 bars @ 4 s", ""],
  ["Fitting", "Injection Parameters", "Hold on Pressure P2", "Comparison", "70 bars @ 3 s", ""],
  ["Pipe-Fitting", "Temperature Parameters", "Temp. Set-up", "Comparison", "", ""],
  ["Pipe-Fitting", "Temperature Parameters", "Barrel Zone 1 Set/Actual (°C)", "Comparison", "182/182", ""],
  ["Pipe-Fitting", "Temperature Parameters", "Barrel Zone 2 Set/Actual (°C)", "Comparison", "180/180", ""],
  ["Pipe-Fitting", "Temperature Parameters", "Barrel Zone 3 Set/Actual (°C)", "Comparison", "178/178", ""],
  ["Pipe-Fitting", "Temperature Parameters", "Barrel Zone 4 Set/Actual (°C)", "Comparison", "176/176", ""],
  ["Pipe-Fitting", "Temperature Parameters", "Barrel Zone 5 Set/Actual (°C)", "Comparison", "174/197", "174/173"],
  ["Pipe-Fitting", "Temperature Parameters", "Barrel Zone 6 Set/Actual (°C)", "Comparison", "", ""],
  ["Pipe-Fitting", "Temperature Parameters", "Barrel Zone 7 Set/Actual (°C)", "Comparison", "", ""],
  ["Pipe-Fitting", "Temperature Parameters", "Barrel Zone 8 Set/Actual (°C)", "Comparison", "", ""],
  ["Fitting", "Temperature Parameters", "Nozzle Temp Set/Actual (°C)", "Comparison", "185/185", ""],
  ["Pipe-Fitting", "Trial Results", "Trial Observations and Findings", "Comparison", "Normal Operation", "OK, No Problem"],
  ["Pipe-Fitting", "Trial Results", "Report", "Comparison", "Normal Operation", "OK, No Problem"]
];

const csvContent = "\uFEFF" + data.map(row => row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(",")).join("\r\n");
fs.writeFileSync("Fittings.csv", csvContent, "utf8");
console.log("Fittings.csv created successfully!");